[[section-introduction-and-goals]]
== Introduction and Goals

=== Requirements Overview

.What is biking2?

The main purpose _biking2_ is keeping track of bicycles and their milages as well as converting _Garmin_ https://en.wikipedia.org/wiki/Training_Center_XML[_Training Center XML_ (tcx)] files to standard https://en.wikipedia.org/wiki/GPS_Exchange_Format[_GPS Exchange Format_ (GPX)] files and storing them in an accessible way.

In addition _biking2_ is used to study and evualate technology, patterns and frameworks. The functional requirements are simple enough to leave enough room for concentration on quality goals.

.Main features

* Store bikes and their milages
* Convert tcx files to GPX files and provide them in a library of tracks
* Visualize those tracks on a map and provide a way to embed them in other webpages
* Visualize biking activities with images
* Optional, near real time, tracking of a biker

The application must only handle exactly one user with write permissions.

Most bike aficionados have problems understanding the question "why more than one bike?", the system should be able to keep track of everything between 2 and 10 bikes for one user, storing 1 total milage per bike and month. All milages per month, year and other metrics should be derived from this running total, so that the user only need to look at his odometer and enter the value.

The application should store an "unlimited" number of tracks.

The images should be collected from https://dailyfratze[Daily Fratze], the source are all images that are tagged with "Radtour". In addition the user should be able to provide an "unlimted" number of "gallery pictures" together with a date and a short description.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) goals for the architecture and/or constraints whose fulfillment is of highest importance to the major stakeholders. Goals that define the architecture’s quality could be:

* availability
* modifiability
* performance
* security
* testability
* usability

.Motivation
If you as an architect do not know how the quality of your work can be judged …

.Form
Simple tabular representation, ordered by priorities

.Background Information
*NEVER* start developing an architecture if these goals have not been put into writing and have not been signed by the major stakeholders.

[WARNING]
===========
We have endured projects lacking defined quality goals much too often.
We do not like to suffer, therefore we are by now highly convinced that
the few hours spent on collecting quality goals are well invested.
PH & GS.
===========

.Sources
The DIN/ISO 92000 Standard contains an extensive set of possible quality goals.Or use chapters 10 – 17 of the http://www.volere.co.uk[VOLERE template] as a starting point .
PH

****

=== Stakeholders

[role="arc42help"]
****
.Contents
A list of the most important persons or organizations that are affected by can contribute to the architecture.

.Motivation
If you do not know the persons participating in or concerned with the project you may get nasty surprises later in the development process. Should your project manager maintain this list, make sure that all the people influencing the architecture are part of it.

.Form
Simple table with role names, person names, their knowledge as pertaining to architecture, their availability, etc.
.Stakeholders
[options="header",cols="<.<1,<.<2, <.<2"]
|===
|Role/Name|Goal/Boundaries|Expected Participation and Contribution
| The name or role of a stakeholder| Why will this stakeholder have an interest in the architecture? | what do you expect as a contribution
|===
****
