[[section-introduction-and-goals]]
== Introduction and Goals

=== Requirements Overview

.What is biking2?

The main purpose _biking2_ is keeping track of bicycles and their milages as well as converting _Garmin_ https://en.wikipedia.org/wiki/Training_Center_XML[_Training Center XML_ (tcx)] files to standard https://en.wikipedia.org/wiki/GPS_Exchange_Format[_GPS Exchange Format_ (GPX)] files and storing them in an accessible way.

In addition _biking2_ is used to study and evualate technology, patterns and frameworks. The functional requirements are simple enough to leave enough room for concentration on quality goals.

.Main features

* Store bikes and their milages
* Convert tcx files to GPX files and provide them in a library of tracks
* Visualize those tracks on a map and provide a way to embed them in other webpages
* Visualize biking activities with images
* Optional, near real time, tracking of a biker

The application must only handle exactly one user with write permissions.

Most bike aficionados have problems understanding the question "why more than one bike?", the system should be able to keep track of everything between 2 and 10 bikes for one user, storing 1 total milage per bike and month. All milages per month, year and other metrics should be derived from this running total, so that the user only need to look at his odometer and enter the value.

The application should store an "unlimited" number of tracks.

The images should be collected from https://dailyfratze[Daily Fratze], the source are all images that are tagged with "Radtour". In addition the user should be able to provide an "unlimted" number of "gallery pictures" together with a date and a short description.

=== Quality Goals

[cols="1,2,3" options="header"]
.Quality Goals
|===
| Nr. | Quality                        | Motivation
| 1   | Understandability              | The functional requirements are simple enough to allow a simple, understandable solution that allows focus on learning about Spring Boot and AngularJS.
| 2   | Efficiency                     | Collecting milage data should be a no brainer: Reading the milage from an odometer and entering it.
| 3   | Interoperability               | The application should provide a simple API that allows access to new clients.
| 4   | Attractiveness                 | Collected milages should be presented in easy to grasp charts.
| 5   | Testability                    | The architecture should allow easy testing of all main building blocks.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
A list of the most important persons or organizations that are affected by can contribute to the architecture.

.Motivation
If you do not know the persons participating in or concerned with the project you may get nasty surprises later in the development process. Should your project manager maintain this list, make sure that all the people influencing the architecture are part of it.

.Form
Simple table with role names, person names, their knowledge as pertaining to architecture, their availability, etc.
.Stakeholders
[options="header",cols="<.<1,<.<2, <.<2"]
|===
|Role/Name|Goal/Boundaries|Expected Participation and Contribution
| The name or role of a stakeholder| Why will this stakeholder have an interest in the architecture? | what do you expect as a contribution
|===
****
