name: build

on:
  push:
    branches:
      - public
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install GPS Babel
        run: sudo apt-get install -y gpsbabel
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify
